DOCS: 태그 조회 api 추가
jiphyeonjeon-42/backend pull request #423
Opened 2023-03-27 06:09 UTC by nyj001012

### 개요
태그 조회 api 추가

### 작업 사항
- 전체 태그 조회 API 추가
- 도서 별 태그 조회 API 추가

### 변경점
- `routes/tags.routes.ts` 추가
- `routes/books.routes.ts`에 태그 조회 API 추가

### 목적
- 태그 조회 기능 구현

### 스크린샷 (optional)

2023-04-04 13:24 UTC, scarf005 requested changes

2023-04-04 13:24 UTC, scarf005 commented on backend/src/routes/tags.routes.ts
> +   *        description: 공개 및 비공개 여부로, 1이면 공개, 0이면 비공개 서브 태그만 가져온다.
키 이름을 `visibility`로 하면 어떻까요? `visibility=public`, `visibility=private` 형식으로 사용하면 좀 더 명확하게 의도를 표현할 수 있을 것 같습니다.

2023-04-04 13:24 UTC, scarf005 commented on backend/src/routes/tags.routes.ts
혹시 서브 태그와 일반 태그의 차이점에 대해서도 추가해주실수 있을까요?

2023-04-24 06:42 UTC, cjho0316 approved these changes
LGTM!

2023-04-24 06:44 UTC, nyj001012 reviewed
수정 완료

2023-04-24 06:45 UTC, merged