User DTO 생성 및 변경 및 적용
jiphyeonjeon-42/backend pull request #449
Opened 2023-04-23 11:33 UTC by jhMin95

FEAT: move user.model.ts and add PrivateUser interface
- User/user.model.ts -> DTO/user.model.ts

### 작업 사항
- DTO 디렉토리 생성.
- User Interface 를 user.dto.ts 파일로 옮기고 password 항목을 제거.
- PrivateUser Interface 생성. password 를 포함하는 인터페이스. auth 에 필요한 부분에 적용

2023-04-23 11:45 UTC, jhMin95 commented
Meta inteface DTO 디렉토리로 옮기기

2023-04-23 11:54 UTC, scarf005 requested changes

2023-04-23 11:54 UTC, scarf005 commented on backend/src/DTO/users.model.ts
PrivateUser가 User 인터페이스에서 password 키만 추가되었다면 [extend](https://www.typescriptlang.org/docs/handbook/2/objects.html#extending-types)를 쓰면 좋을 것 같습니다.
```ts
export interface PrivateUser extends User {
  password: string,
}
```

2023-04-24 13:54 UTC, scarf005 approved these changes

2023-04-25 11:15 UTC, middlefitting approved these changes

2023-04-26 06:34 UTC, merged