회원가입 개선
jiphyeonjeon-42/backend pull request #540
Opened 2023-06-28 05:44 UTC by middlefitting

### 개요
- 회원가입 보안을 개선합니다.

### 작업 사항
- [x] 인트라 회원가입시 비밀번호를 UUID를 통해 랜덤값으로 설정
- [x] 기본 회원가입시  @student.42seoul.kr 를 금지하도록 설정

2023-07-05 07:32 UTC, nyj001012 approved these changes
LGTM

2023-07-11 02:28 UTC, scarf005 requested changes

2023-07-11 02:28 UTC, scarf005 commented on backend/src/auth/auth.controller.ts
> +import { randomUUID } from 'crypto';
```suggestion
import { randomUUID } from 'node:crypto';
```

 [randomUUID가](https://nodejs.org/docs/latest-v18.x/api/crypto.html#cryptorandomuuidoptions) node 빌트인 모듈 임을 [명시적으로 표시](https://nodejs.org/docs/latest-v18.x/api/esm.html#node-imports)해주면 좋을 것 같습니다

2023-07-11 02:28 UTC, scarf005 commented on backend/package.json
> +    "uuid": "^9.0.0",
```suggestion
```

현재 PR 구현에서 node 빌트인 crypto 모듈에서 제공하는 [randomUUID](https://nodejs.org/docs/latest-v18.x/api/crypto.html#cryptorandomuuidoptions)를 사용하고 있어 해당 패키지는 사용중이지 않은 것 같습니다.

2023-07-11 02:49 UTC, scarf005 commented on backend/src/users/users.controller.ts
> +    return next(new ErrorResponse(errorCode.INVALID_INPUT, status.BAD_REQUEST));
```suggestion
    return next(new ErrorResponse(errorCode.STUDENT_42_SUBSCRIPTION_FORBIDDEN, status.BAD_REQUEST));
```

현 상황에서는 새로 추가된 오류 코드인 `STUDENT_42_SUBSCRIPTION_FORBIDDEN`를 추가하는 것이 조금 더 적절할 것 같아요

2023-07-12 06:09 UTC, middlefitting commented on backend/package.json
> +    "uuid": "^9.0.0",
빌트인 모듈 내에서 해결할 수 있는 부분이었군요. 불필요한 패키지를 설치할 뻔 했네요. 감사합니다

2023-07-12 06:10 UTC, middlefitting commented on backend/src/users/users.controller.ts
> +    return next(new ErrorResponse(errorCode.INVALID_INPUT, status.BAD_REQUEST));
수정하였습니다! 꼼꼼하게 체크해주셔서 감사드립니다!

2023-07-12 07:05 UTC, scarf005 approved these changes
LGTM

2023-07-12 07:24 UTC, merged