feat: 태그 메인 페이지 api 요청
jiphyeonjeon-42/backend pull request #636
Opened 2023-07-31 23:51 UTC by nyj001012

### 개요
태그 메인 페이지 API 추가

### 작업 사항

### 변경점

### 목적

### 스크린샷 (optional)

2023-08-01 00:07 UTC, scarf005 reviewed
![image](https://github.com/jiphyeonjeon-42/backend/assets/54838975/d235760f-f82f-4ec8-b1bd-ba5cdb4ace9e)

혹시 태그와 연관된 커밋은 첫 두 커밋뿐일까요?

- 0878cad65189dc4893c7dfa2e10273a2f72367a9
- c860b598777b87b849a41a5aee85f1af5898f7d4

2023-08-01 01:00 UTC, nyj001012 commented
> ![image](https://github.com/jiphyeonjeon-42/backend/assets/54838975/d235760f-f82f-4ec8-b1bd-ba5cdb4ace9e)
> 
> 혹시 현재 PR과 연관된 커밋은 첫 두 커밋뿐일까요?
> 
> - 0878cad65189dc4893c7dfa2e10273a2f72367a9
> - c860b598777b87b849a41a5aee85f1af5898f7d4
> 

넵 맞아요

2023-08-01 01:14 UTC, scarf005 commented
그렇다면 `git rebase --onto` 기능을 사용해 커밋 둘만 남겨보는 방법을 추천드립니다.

```
# 첫 두 커밋을 복사해 origin/develop 위에 얹습니다.
git rebase \
	--onto origin/develop \
	0878cad65189dc4893c7dfa2e10273a2f72367a9^ \
	c860b598777b87b849a41a5aee85f1af5898f7d4

# 기존 브랜치 (커밋 x18)를 제거합니다
git branch -D 582-태그-메인-페이지-api-요청

# rebase 된 새 브랜치(커밋 x2) 이름을 기존 브랜치명으로 수정합니다
git branch -m 582-태그-메인-페이지-api-요청

git push -f
```

## 참고 링크
- https://git-scm.com/docs/git-rebase
- https://womanonrails.com/git-rebase-onto
- https://driip.me/3e206178-8e6c-4519-be35-55b5afeab30b

2023-08-01 02:29 UTC, nyj001012 commented
오... 지금 봤네요. 이후에 커밋 5개가 추가되었으니 7개 항목에 대해 cherry pick하면 되는 거겠죠?

2023-08-01 02:34 UTC, scarf005 commented
넵 7개 항목에 대해 cherry picking을 하는 방식이 가장 간단할 것 같습니다.
~~git rebase --interactive를 쓰면 더 편리할지도?~~

2023-08-01 02:46 UTC, nyj001012 commented
성공했다면 제가 추가한 커밋들만 나와야 할텐데... 계속 시도해보다 점심 때까지 안 되면 dm으로 여쭤봐도 될까요?

2023-08-02 13:00 UTC, scarf005 requested changes

2023-08-02 13:00 UTC, scarf005 commented on backend/src/entity/entities/VTagsSuperDefault.ts
> +    .union((subQuery) => subQuery
타입 체킹에 실패합니다. 혹시 addSelect일까요?

2023-08-06 14:15 UTC, nyj001012 commented on backend/src/entity/entities/VTagsSuperDefault.ts
> +    .union((subQuery) => subQuery
아뇨아뇨 andWhere 맞아요

2023-08-09 07:06 UTC, nyj001012 commented on backend/src/entity/entities/VTagsSuperDefault.ts
> +    .union((subQuery) => subQuery
`createQuerybuilder().union()` 부분이 문제였네요. TypeORM에서는 union 함수를 지원하지 않아서 View entity의 expression을 raw query로 구현했습니다.

2023-08-09 07:18 UTC, scarf005 approved these changes
![image](https://github.com/jiphyeonjeon-42/backend/assets/54838975/4e73b7a1-652d-485c-803d-9bd37b1a00bc)

LGTM

2023-08-09 07:45 UTC, merged