616 v2 리팩토링 stock api
jiphyeonjeon-42/backend pull request #663
Opened 2023-08-12 08:22 UTC by JeongJiHwan

### 개요

stock api 에 ts-rest 적용하여 리팩토링

### 작업 사항

contract 작성
controller 작성
service 작성
error 처리

### 질문

- 재고조회(search) api(page와 limit 외에 별도의 인자가 없습니다) 에서 발생할 수 있는 에러에 관한 조언을 구합니다.

- 또한 재고조회에서 updatedAt 값이 zod에서 타입변환하는데 오류를 보이고 있습니다.
updatedAt: '2023-03-12-16:19:26' 와 같은 형식으로 조회되는데 %d와 %T 사이에 있는 "-"가 문제를 일으키는게 아닌가하여 entity/entities/VStock.ts 에서 queryBuilder 부분을 수정해보았으나 반환되는 값은 그대로여서 이 부분에 대한 조언도 구합니다.

수정을 위한 PR로 피드백 부탁드립니다.

2023-08-12 09:05 UTC, scarf005 requested changes

2023-08-12 09:05 UTC, scarf005 commented on backend/src/entity/entities/VStock.ts
> +    .addSelect("date_format(book.updatedAt, '%Y-%m-%d %T')", 'updatedAt')
https://github.com/jiphyeonjeon-42/backend/blob/4fa678527c17aad537cff683dc7ac001ca87c6c1/backend/src/app-data-source.ts#L6-L14

@nyj001012 님에게 여쭤본 결과, 현재 [`synchronize` 옵션](https://orkhan.gitbook.io/typeorm/docs/faq#how-do-i-update-a-database-schema)이 꺼져 있어 typescript 엔티티를 변경해도 typeorm이 DB에 변경을 하지 않은 것으로 보입니다.

현재 [프론트엔드에서 stock의 `updatedAt` 필드를 사용중이지 않기 때문에](https://github.com/search?q=repo%3Ajiphyeonjeon-42%2Ffrontend%20updatedAt&type=code), 우선은 ts-rest 필드 타입을 `z.string()`으로 완화하는 우회책을 사용하고, 후속 PR에서 해결해보면 어떨까요?

2023-08-12 09:05 UTC, scarf005 commented on contracts/src/stock/schema.ts
> +			updatedAt: z.string().pipe(z.coerce.date()),
```suggestion
			updatedAt: z.string(),
```

2023-08-13 02:03 UTC, JeongJiHwan commented on backend/src/entity/entities/VStock.ts
> +    .addSelect("date_format(book.updatedAt, '%Y-%m-%d %T')", 'updatedAt')
좋습니다!

2023-08-13 03:17 UTC, scarf005 approved these changes
![image](https://github.com/jiphyeonjeon-42/backend/assets/54838975/bfd47cdf-c2bd-4321-b0bb-ef4941e37a4e)

LGTM!

2023-08-13 03:17 UTC, merged