672 books api 스펙 정리
jiphyeonjeon-42/backend pull request #676
Opened 2023-08-17 03:35 UTC by JeongJiHwan

### 개요
books api 스펙 contracts 정리

### 작업 사항
get: books/info/search
get: books/info/tag
get: books/info -> /books/info/sorted
get: books/info/:id
get: books/search
get: books/create
get: books/:bookId
post: books/create
patch: books/update
patch: books/donator

2023-08-17 07:36 UTC, scarf005 requested changes
작성하시느라 수고 많으셨어요! 다만 [zod의 객체 메서드](https://zod.dev/?id=objects)들을 사용하면 중복되는 코드를 많이 줄일 수 있을 것 같아요. 또, 상태값의 경우에는 숫자 대신 [리터럴 유니언 타입](https://www.typescriptlang.org/ko/docs/handbook/2/everyday-types.html#리터럴-타입)을 사용하면 좀 더 명확하게 의도를 전달할 수 있을 것 같아요.

또 궁금한 점이 있다면 언제라도 답글을 달아주세요!

2023-08-17 07:36 UTC, scarf005 commented on contracts/src/books/schema.ts
잘 작성해 주셨습니다. 다만, 스키마에서 `query`, `sort`, `page` 등 재사용하는 필드가 많이 생기는데, [zod의 `.extend()`](https://zod.dev/?id=extend) 메서드를 사용하면 중복되는 코드량을 줄이실 수 있을 거에요.

2023-08-17 07:36 UTC, scarf005 commented on contracts/src/books/schema.ts
> +});
`createBookBodySchema`와 `updateBookBodySchema`는 모두 `bookInfoSchema`에서 조금씩만 변형된 형태입니다. 그렇다면 [zod의 .pick()과 .omit()을 써보면 어떨까요?](https://zod.dev/?id=pickomit)

2023-08-17 07:36 UTC, scarf005 commented on contracts/src/books/schema.ts
> +			status: positiveInt.gte(0).lte(2),
도서 상태를 숫자로 보내준다면 프론트엔드에서 값을 받았을 때, 또 디버깅 할때 status가 어떤 의미인지 확인하기 어려울 수도 있을 것 같아요. 이럴때는 [zod의 .enum()](https://zod.dev/?id=zod-enums) 기능을 사용하면, 도서의 상태를 처음 보아도 잘 이해할 수 있을 것 같아요.

2023-08-20 06:40 UTC, JeongJiHwan commented on contracts/src/books/schema.ts
> +			status: positiveInt.gte(0).lte(2),
status가 0~2 값을 가진다는것 까지만 확인되고 어떻게 사용되는지를 확인하지 못해서 이부분은 프론트 개발하시는 분께 여쭤봐야할까요?

2023-08-20 06:41 UTC, JeongJiHwan commented on contracts/src/books/schema.ts
> +});
zod의 기능을 전혀 활용하지 못하고 있었네요 ㅎ.. 확인해보겠습니다!

2023-08-21 01:03 UTC, jimin52 commented on contracts/src/books/schema.ts
> +			status: positiveInt.gte(0).lte(2),
erd cloud 페이지 들어가면 어떤 값인지 확인하실 수 있습니다
복사가 막혀있네요 ㅜㅜ 링크 드릴게요
https://www.erdcloud.com/d/6rZ4ae7Ft6CrK83RT

2023-08-21 01:03 UTC, jimin52 commented on contracts/src/books/schema.ts
> +			status: positiveInt.gte(0).lte(2),
<img width="92" alt="스크린샷 2023-08-20 오후 7 04 42" src="https://github.com/jiphyeonjeon-42/backend/assets/45284810/5bd91059-32df-490d-b41e-fa80140b1f59">
복사가 안되어서 캡처했습니다

2023-08-21 01:05 UTC, scarf005 commented on contracts/src/books/schema.ts
> +			status: positiveInt.gte(0).lte(2),
```ts
status: z.enum(["ok", "lost", "damaged", "booked"])
```
이런 식으로 작성할수 있을 것 같아요!

2023-08-21 10:37 UTC, jhMin95 approved these changes
LGTM

2023-08-21 10:53 UTC, jhMin95 commented
뒤늦게 지정도서가 뭔지 기억났습니다.
동물책같은 과제에 필수적이면서 자주 빌려가는 책들을 대출 불가하도록 (클러스터에서만 읽을 수 있게) 처리하려고 했었던 것이었습니다.
현재 딱히 쓰이고 있지는 않은 값입니다

2023-08-22 02:57 UTC, JeongJiHwan commented on contracts/src/books/schema.ts
> +});
book, bookinfo, book&bookinfo 등 아직 정리가 되지 않아서 이후 api 구현하면서 수정해보도록 하겠습니다.

2023-08-22 10:12 UTC, scarf005 approved these changes
수고 많으셨습니다!

2023-08-22 10:46 UTC, merged