V2 Tags 스펙 정리
jiphyeonjeon-42/backend pull request #697
Opened 2023-08-25 07:26 UTC by nyj001012

### 개요

### 작업 사항

### 변경점

### 목적

### 스크린샷 (optional)

2023-08-27 05:34 UTC, scarf005 commented on contracts/src/tags/index.ts
> +        500: serverErrorSchema,
```suggestion
        401: forbiddenSchema,
```
400번 500번대 오류는 생략해도 괜찮을 것 같아요.

400 (올바르지 않은 입력): 프론트엔드 contracts에서 zod로 이미 검증하고 있어서
500 (서버 오류): 모든 API 요청에 공통적으로 나오기 때문에

2023-08-27 06:25 UTC, nyj001012 commented on contracts/src/tags/index.ts
> +        500: serverErrorSchema,
앗 맞네요, 그러면 400부터 500번대는 tag의 다른 api에서도 생략해서 다시 PR 올리겠습니다 :)

2023-08-27 06:49 UTC, scarf005 requested changes

2023-08-27 06:49 UTC, scarf005 commented on contracts/src/tags/index.ts
> +        200: modifyTagResponseSchema,
```suggestion
        204: z.null()
```

추가로 반환해야 하는 정보가 없기 때문에, [204 No Content](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204)를 사용해 단순화하는것을 제안합니다.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH#response

2023-08-27 06:49 UTC, scarf005 commented on contracts/src/tags/index.ts
> +        900: incorrectTagFormatSchema,
```suggestion
```
v1과 달리 zod 스키마에서 이미 태그 양식을 검증하기 때문에 해당 오류 코드가 없어도 괜찮을 것 같아요.

https://github.com/jiphyeonjeon-42/backend/blob/16421c50fad1d6689d0a446e4ea6283f4a404170/backend/src/v1/tags/tags.controller.ts#L193-L196

2023-08-27 06:49 UTC, scarf005 commented on contracts/src/tags/index.ts
> +        906: defaultTagCannotBeModifiedSchema,
```suggestion
        400: z.union([alreadyExistTagSchema, defaultTagCannotBeModifiedSchema]),
```
존재하는 HTTP 오류 코드를 사용하면 의도를 더 명확히 표현할 수 있을 것 같아요. 어떻게 생각하시나요?

참고 링크: https://softwareengineering.stackexchange.com/a/342896

2023-08-27 07:37 UTC, nyj001012 commented on contracts/src/tags/index.ts
> +        906: defaultTagCannotBeModifiedSchema,
아 400이긴 한데 따로 400으로 빼긴 애매해서 그냥 커스텀으로 했더니 저렇게 하면 됐었네요..!

2023-08-28 05:46 UTC, scarf005 commented on contracts/src/tags/index.ts
> +        906: defaultTagCannotBeModifiedSchema,
혹시 다른 엔드포인트 반환값에도 900번대 대신 HTTP 오류 코드를 적용하는것에 대해 어떻게 생각하시나요?

2023-08-28 08:33 UTC, nyj001012 commented on contracts/src/tags/index.ts
> +        906: defaultTagCannotBeModifiedSchema,
엄청 좋죠! 사실 커스텀 에러 코드를 E_001234 이런 형식이 아니라 숫자로 쓰는 것에 대해 회의적인 입장입니다

2023-08-28 08:52 UTC, scarf005 requested changes

2023-08-28 08:52 UTC, scarf005 commented on contracts/src/tags/index.ts
- `204`: https://github.com/jiphyeonjeon-42/backend/pull/697#discussion_r1306609998
- `incorrectTagFormatSchema`: https://github.com/jiphyeonjeon-42/backend/pull/697#discussion_r1306610143
https://github.com/jiphyeonjeon-42/backend/pull/697#discussion_r1306610447
- `alreadyExistTagSchema, defaultTagCannotBeModifiedSchema`: https://github.com/jiphyeonjeon-42/backend/pull/697#discussion_r1306610447

이전 리뷰에서 했던 변경에 이어서, `tagContract`의 나머지 900번대 responses들에도 같은 변경 사항을 적용하면 좋을 것 같아요!

2023-08-28 08:52 UTC, scarf005 commented on contracts/src/tags/index.ts
> +        901: NoAuthorityToModifyTagSchema,
권한 오류인 경우에는 `contracts/src/shared.ts`의 `forbiddenSchema`를 사용하면 코드의 통일성을 높일 수 있을 것 같아요.

https://github.com/jiphyeonjeon-42/backend/blob/112e19ac2f6ef7266f8acb2be9582f66f120878b/contracts/src/shared.ts#L42

2023-08-28 08:52 UTC, scarf005 commented on contracts/src/tags/schema.ts
> +  }),
```suggestion
  bookInfoId: bookInfoIdSchema,
```

https://github.com/jiphyeonjeon-42/backend/blob/112e19ac2f6ef7266f8acb2be9582f66f120878b/contracts/src/shared.ts#L7

`bookInfoIdSchema`와 같이 기존에 있던 스키마를 재활용하면 코드 중복을 줄일 수 있을 것 같아요.

2023-08-28 08:52 UTC, scarf005 commented on contracts/src/tags/schema.ts
> +  }),
```suggestion
  subTagIds: z.array(tagId)
```
`tagIdSchema`에 이미 정의된 tagId를 활용해도 좋을 것 같아요

2023-08-28 08:52 UTC, scarf005 commented on contracts/src/tags/schema.ts
> +  }),
```suggestion
  id: tagId,
```

2023-09-04 23:03 UTC, scarf005 commented on contracts/src/index.ts
> +    // tags: tagContract,
백엔드에서 V2 태그 서비스가 구현이 되지 않았기 때문에 깃허브 액션에서 타입 오류가 발생했습니다.

2023-09-04 23:04 UTC, scarf005 approved these changes
아직 백엔드에서 `tagContract`가 구현이 되지 않아 깃허브 액션에서 타입 오류가 발생했으나, tag 스펙 정리가 목적인 PR이기 때문에 contract에서 주석 처리만 했습니다. 수고 많으셨어요!

2023-09-05 03:17 UTC, merged