JIP-96 - JIP-96-users-api-merge
jiphyeonjeon-42/backend pull request #71
Opened 2022-06-07 10:31 UTC by jhMin95

### 개요
users api 완성

### 작업 사항
- users/search
- users/create
- users/update
- users/myupdate
- 위 api들의 wagger 작성

### 목적
- 오류가 있겠지만 일단 돌려봤고 돌아는 갑니다..

2022-06-08 07:12 UTC, evelon requested changes

2022-06-08 07:12 UTC, evelon commented on backend/src/routes/users.routes.ts
>   *      requestBody:
get에 requestBody가 있을 수 있나요?

2022-06-08 07:42 UTC, jhMin95 commented on backend/src/routes/users.routes.ts
>   *      requestBody:
전에 post 로 보내려다가 get 으로 수정하고 변경을 안해놨네요.
실제 코드에서는 query로 받습니다. 변경해놓을게요

2022-06-08 08:00 UTC, YeonSeong-Lee commented on backend/src/users/users.service.ts
> +    l.userId as userId, bi.title as title, DATE_ADD(l.updatedAt, INTERVAL 14 DAY) as duedate
반납 예정일을 updatedAt에서 14일 더한걸로 한 이유가 있을까요? createdAt이 아니라.

2022-06-10 13:23 UTC, YeonSeong-Lee commented on backend/src/users/users.model.ts
> +  intraId?: number;
intraID?: number 뒤에` , ` 가 아니라 `;`로 해도 괜찮은건가요?
```suggestion
  intraId?: number,
```

2022-06-11 02:22 UTC, YeonSeong-Lee commented on backend/src/users/users.model.ts
> +  intraId?: number;
`;` 울 `,`으로 수정하였습니다.

2022-06-11 02:30 UTC, YeonSeong-Lee commented on backend/src/users/users.service.ts
> +    l.userId as userId, bi.title as title, DATE_ADD(l.updatedAt, INTERVAL 14 DAY) as duedate
createdAt 으로 변경

2022-06-11 03:19 UTC, YeonSeong-Lee requested changes

2022-06-11 03:19 UTC, YeonSeong-Lee commented on backend/src/users/users.type.ts
> +}
`nickName`을 `nickname`으로 수정 부탁드립니다.

2022-06-11 03:25 UTC, YeonSeong-Lee commented on backend/src/users/users.type.ts
> +}
변경 완료

2022-06-11 03:26 UTC, YeonSeong-Lee approved these changes

2022-06-12 04:59 UTC, evelon approved these changes

2022-06-13 01:42 UTC, merged