feat: v2 리팩토링 book api
jiphyeonjeon-42/backend pull request #746
Opened 2023-09-05 08:26 UTC by JeongJiHwan

### 작업 사항
  v2 books routes 구현
  [GET]
    v2/books/info/search
    v2/books/info/tag
    v2/books/info/sorted
    v2/books/info/:id
    v2/books/search
    v2/books/:id
  [PATCH]
    v2/books/update
    v2/books/donator

### 남은 작업
[GET]
    v2/books/create
[POST]
    v2/books/create

2023-09-05 08:55 UTC, scarf005 requested changes
https://github.com/jiphyeonjeon-42/backend/pull/746/commits/f6285765bec5c7917b05e726f1b2d9778bc59d25

V1에서는 `status`값으로 `number`를 반환하기 때문에 `enum`으로 바꾸어주셨군요!

하지만 이렇게 바꾸게 된다면 프론트엔드에는 API 스웨거 문서에서 `status`값이 `number`라는 정보만 얻을 수 있기에 API의 동작을 이해하는데 어려움이 생길 수 있을 것 같아요.

기존 V1 API를 유지한 상태에서 V2 API를 처음부터 작성하는 것이기 때문에, V1 API의 동작을 꼭 재현하지 않아도 괜찮을 것 같아요.

2023-09-05 09:03 UTC, scarf005 commented on backend/src/v2/books/service.ts
혹시 이 주석들은 어떤 역할일까요?

2023-09-05 09:43 UTC, scarf005 requested changes

2023-09-05 09:43 UTC, scarf005 commented on backend/src/entity/entities/VSearchBookByTag.ts
엔티티 수정사항이 적용되려면 개발 DB와 production DB 모두 같은 column이 추가되어야 하기 때문에, PR 내용에 해당 내용을 추가해주시면 마이그레이션 하는데 도움이 될 것 같아요.

2023-09-05 09:43 UTC, scarf005 commented on backend/src/v2/books/repository.ts
> +					.executeTakeFirst();
```suggestion
	const isLended = await db
					.selectFrom('lending')
					.where('bookId', '=', id)
					.where('returnedAt', 'is', null)
					.executeTakeFirst();

	const book = await db
					.selectFrom('book')
					.where('id', '=', id)
					.where('status', '=', 0)
					.executeTakeFirst();

	const isReserved = await db
					.selectFrom('reservation')
					.where('bookId', '=', id)
					.where('status', '=', 0)
					.executeTakeFirst();

	return book && !isLended && isReserved;
```

1. count1, count2보다는 원하는 동작을 반영한 변수명을 사용하면 이해에 도움이 될 것 같아요.
2. 컬럼의 수가 아닌 존재 유무만 확인하는 것이기 때문에, `executeTakeFirst`만 써서 구현하면 코드를 더 간략화할수 있을 것 같아요.

2023-09-05 09:43 UTC, scarf005 commented on backend/src/v2/books/repository.ts
> +		return 0;
혹시 `boolean` 대신 `number`를 반환해주신 이유가 있으실까요?

2023-09-05 09:43 UTC, scarf005 commented on backend/src/v2/books/repository.ts
> +		.executeTakeFirst();
```suggestion
const bookInfoBy = () =>
    db
      .selectFrom('book_info')
      .select([
        'book_info.id',
        'book_info.title',
        'book_info.author',
        'book_info.publisher',
        'book_info.isbn',
        'book_info.image',
        'book_info.publishedAt',
        'book_info.createdAt',
        'book_info.updatedAt'
      ])

export const getBookInfosSorted = (limit: number) =>
  bookInfoBy()
    .leftJoin('book', 'book_info.id', 'book.infoId')
    .leftJoin('category', 'book_info.categoryId', 'category.id')
    .leftJoin('lending', 'book.id', 'lending.bookId')
    .select('category.name as category')
    .select(({ eb }) => eb.fn.count('lending.id').as('lendingCnt'))
    .limit(limit)
    .groupBy('id')

export const searchBookInfoSpecById = async ( id: number ) =>
  bookInfoBy()
    .select(({ selectFrom }) => [
      selectFrom('category')
      .select('name')
      .whereRef('category.id', '=', 'book_info.categoryId')
      .as('category'),
    ])
    .where('id', '=', id)
    .executeTakeFirst();
```
두 쿼리가 select하는 column이 거의 동일하기 때문에, 공통된 부분을 별개의 함수로 만들면 DRY 원칙을 지킬 수 있을 것 같아요.

#### 참고 링크
https://kysely.dev/docs/getting-started#querying (쿼리 재사용하기)

2023-09-07 03:50 UTC, JeongJiHwan commented on backend/src/entity/entities/VSearchBookByTag.ts
쿼리빌더에서는 select 하는 칼럼이 아래 클래스에는 없어서 해당 부분만 추가한거라 엔티티 수정사항은 따로 없습니다!

2023-09-07 03:54 UTC, scarf005 commented on backend/src/entity/entities/VSearchBookByTag.ts
![image](https://github.com/jiphyeonjeon-42/backend/assets/54838975/a3a0ec4a-cdb6-48f9-9f5d-d5117dbdaf0f)

확인했습니다. 커밋 메시지나 PR 본문에 관련 내용을 적어주시면 더 의도를 빠르게 확인할 수 있을 것 같아요

2023-09-07 03:54 UTC, JeongJiHwan commented on backend/src/v2/books/service.ts
books/create 부분이 아직 남아서 주석 정리를 하지 않았네요. 삭제하도록 하겠습니다.

2023-09-07 03:54 UTC, JeongJiHwan commented on backend/src/v2/books/repository.ts
> +		return 0;
js 에서는 0이 false가 아닌가요?

2023-09-07 03:56 UTC, JeongJiHwan commented on backend/src/v2/books/repository.ts
> +					.executeTakeFirst();
확실히 변수명에 원하는 동작을 반영하니 보기 편하군요!!

2023-09-07 03:58 UTC, scarf005 commented on backend/src/v2/books/repository.ts
> +		return 0;
0이 false로 인식되는 것은 맞지만, 함수 구현을 확인하지 않고서는 `number`라는 반환값만 보고서는 `1`과 `0`만 반환할지, 아니면 다른 값을 반환할지 알기 어렵습니다.

2023-09-07 03:59 UTC, JeongJiHwan commented on backend/src/v2/books/repository.ts
> +		.executeTakeFirst();
작성하면서도 너무 중복된다고 생각했는데 감사합니다!

2023-09-07 06:00 UTC, JeongJiHwan commented
> [f628576](https://github.com/jiphyeonjeon-42/backend/commit/f6285765bec5c7917b05e726f1b2d9778bc59d25)
> 
> V1에서는 `status`값으로 `number`를 반환하기 때문에 `enum`으로 바꾸어주셨군요!
> 
> 하지만 이렇게 바꾸게 된다면 프론트엔드에는 API 스웨거 문서에서 `status`값이 `number`라는 정보만 얻을 수 있기에 API의 동작을 이해하는데 어려움이 생길 수 있을 것 같아요.
> 
> 기존 V1 API를 유지한 상태에서 V2 API를 처음부터 작성하는 것이기 때문에, V1 API의 동작을 꼭 재현하지 않아도 괜찮을 것 같아요.

db에서 반환해주는 값이 Number라서 zod 반환타입을 맞추다보니 이런식으로 바뀌게 됐는데 프론트에서도 쉽게 확인할 수 있는 다른 방법에 뭐가 있을까요?

2023-09-07 06:10 UTC, scarf005 commented
> db에서 반환해주는 값이 Number라서 zod 반환타입을 맞추다보니 이런식으로 바뀌게 됐는데 

db에서 반환한 값(엔티티)는 비즈니스 로직에 사용되는 값(DTO)과 차이가 있을 수 있기 때문에, 서버에서 DB에 쿼리 후 명시적으로 값을 변환하는 것을 추천드립니다.

참고 링크: https://wildeveloperetrain.tistory.com/101

> 프론트에서도 쉽게 확인할 수 있는 다른 방법에 뭐가 있을까요?

`case` 문을 사용해 db 쿼리단에서 매핑을 해주면 될 것 같습니다. `619-v2-리팩토링-book-api`에 대한 PR을 열어 변경 방법을 설명드릴게요

참고 링크:
- https://extbrain.tistory.com/46
- https://kysely-org.github.io/kysely-apidoc/interfaces/ExpressionBuilder.html#case

2023-09-07 10:23 UTC, scarf005 approved these changes
다음에는 조금 더 작은 단위(예시: contracts PR, backend PR 1개씩)로 쪼개면 리뷰할 때 도움이 될 것 같아요. 수고 많으셨어요!

2023-09-07 14:48 UTC, merged