778 auth 관련 api 무조건 200 리턴 버그
jiphyeonjeon-42/backend pull request #779
Opened 2023-09-21 08:09 UTC by jimin52

### 개요
/auth 로 접속하면 1번 유저를 리턴하는 버그가 있었음

### 작업 사항
users/search 에 librarian validate 추가
users/me 엔드포인트 추가. 로그인한 유저만 가능하도록 쿠키에서 값 받게 변경

### 목적
본인 정보만 me 로 조회할 수 있게 하고 모든 유저 정보 접근은 사서만 가능하게 설정

2023-09-24 12:51 UTC, scarf005 requested changes
![image](https://github.com/jiphyeonjeon-42/backend/assets/54838975/be201b48-b7ec-4fff-8a97-ae0563cdff9f)
![image](https://github.com/jiphyeonjeon-42/backend/assets/54838975/c58b50d5-6812-4882-b3d4-d3cef719fa71)

수정 후에도 동일한 오류가 발생하고 있습니다. 사용한 명령어는 다음과 같습니다.

```sh
$ curl -I 'localhost:3000/api/auth/me'
$ curl -I 'localhost:3000/api/auth/me?id=100'
```

2023-09-25 13:43 UTC, jimin52 commented
헷갈려서 한참을 찾았네요.. 제가 만든건 `users/me` api 입니다.
옛날에 만들었던 `auth/me` api 에 버그가 있네요 ㅜㅜ

2023-09-26 01:22 UTC, jimin52 commented
> ![image](https://user-images.githubusercontent.com/54838975/270164996-be201b48-b7ec-4fff-8a97-ae0563cdff9f.png) ![image](https://user-images.githubusercontent.com/54838975/270165031-c58b50d5-6812-4882-b3d4-d3cef719fa71.png)
> 
> 수정 후에도 동일한 오류가 발생하고 있습니다. 사용한 명령어는 다음과 같습니다.
> 
> ```shell
> $ curl -I 'localhost:3000/api/auth/me'
> $ curl -I 'localhost:3000/api/auth/me?id=100'
> ```

2023-09-26 01:28 UTC, scarf005 reviewed
![image](https://github.com/jiphyeonjeon-42/backend/assets/54838975/428755d3-d838-4861-b39f-80d42414b2b0)
![image](https://github.com/jiphyeonjeon-42/backend/assets/54838975/d5eac7a3-da13-464a-bdf6-41ff443271d3)

```sh
curl -I 'http://localhost:3000/api/users/me'
curl -I 'http://localhost:3000/api/users/me?id=3'
```
500 에러가 발생하는 것 같습니다.

2023-09-26 03:01 UTC, scarf005 approved these changes
![image](https://github.com/jiphyeonjeon-42/backend/assets/54838975/99c865c2-a04b-40d4-8369-42cdbd818bce)

잘 되는 것 같네요. 수고하셨습니다!

2023-10-01 05:23 UTC, merged