Jip 150 슬랙봇이 알람을 보냅니다
jiphyeonjeon-42/backend pull request #87
Opened 2022-06-19 13:01 UTC by evelon

### 개요
슬랙봇이 여러 종류의 알림을 보냅니다.

### 작업 사항
예약 1순위자에게 알림을 보냅니다.
대출 시 알람을 보냅니다.
예약 만료 시에 알림을 보냅니다.
대출 만료 3일 전 알림을 보냅니다.
연체 시 알림을 보냅니다.

### 변경점
src/notification/, src/notification/notification.service.ts가 생성되었습니다.
src/utils/scheduler에 notification들이 등록되었습니다.

### 목적

### 스크린샷 (optional)

2022-06-19 13:57 UTC, YeonSeong-Lee requested changes

2022-06-19 13:57 UTC, YeonSeong-Lee commented on backend/src/slack/slack.controller.ts
> +      next(new ErrorResponse(errorCode.queryExecutionFailed, status.INTERNAL_SERVER_ERROR));
errorCode 들 대문자로 수정했습니다!

[지라 링크](https://42jiphyeonjeon.atlassian.net/browse/JIP-157)

2022-06-19 13:57 UTC, YeonSeong-Lee commented on backend/src/utils/scheduler.ts
> +};
testScheduler가 남아있는 이유가 있을까요?

2022-06-19 14:35 UTC, YeonSeong-Lee requested changes

2022-06-19 14:35 UTC, YeonSeong-Lee commented on backend/src/slack/slack.controller.ts
> +    }
```suggestion
  } catch (error: any) {
    const errorNumber = parseInt(error.message, 10);
    if (errorNumber >= 400 && errorNumber < 500) {
      next(new ErrorResponse(error.message, status.BAD_REQUEST));
    } else if (error.message === 'DB error') {
      next(new ErrorResponse(errorCode.QUERY_EXECUTION_FAILED, status.INTERNAL_SERVER_ERROR));
    } else {
      logger.error(error.message);
      next(new ErrorResponse(errorCode.UNKNOWN_ERROR, status.INTERNAL_SERVER_ERROR));
    }
```

2022-06-19 14:40 UTC, YeonSeong-Lee commented on backend/src/slack/slack.controller.ts
> +    }
[PR](https://github.com/jiphyeonjeon-42/backend-express/pull/86)에서 에러코드들은 상수항이기 때문에 대문자가 더 적절하다고 판단하여 대문자로 변경되었습니다.

2022-06-20 02:58 UTC, evelon commented on backend/src/utils/scheduler.ts
> +};
삭제하였습니다.

2022-06-20 02:59 UTC, evelon commented on backend/src/slack/slack.controller.ts
> +    }
수정하였습니다.

2022-06-20 03:21 UTC, YeonSeong-Lee approved these changes
thanks

2022-06-20 04:04 UTC, merged